### ISSUE TITLE
Transactions: Transfers Filter

### ISSUE THREAD

**Issue by starpause** [NEAR-Edu/stats.gallery#54]
![image](https://user-images.githubusercontent.com/408953/135139539-5cf68f9a-8078-4928-9d76-dbf39d401c1f.png)

**Is your feature request related to a problem? Please describe.**
Right now it is only possible to filter by All | Incoming | Outgoing | Function Call.

**Describe the solution you'd like**
I'd like to be able to filter by Transfers. 

Less important, but I also don't see transfers listed in the circular graph. It would be interesting to see red/out and green/in slices there.

**Comment by encody** [comment]
Thanks for submitting the issue. For the time being, you can view transfers by using the Balance widget on the main dashboard page.

<img width="237" alt="brave_2021-09-28-13-30-42" src="https://user-images.githubusercontent.com/7459638/135145185-868c1ca0-bb84-42d7-b66e-f35a78910488.png">

**Comment by starpause** [comment]
Thanks for the tip! I noticed Balance widget button but view transfers there only gives me the last few transactions, history isn't as deep as the transactions page.

**Comment by encody** [comment]
New UI filter controls look like so:

<img width="584" alt="brave_2021-11-02-16-02-24" src="https://user-images.githubusercontent.com/7459638/139951238-4f37614c-96cb-47ec-8824-12bf286c5d3d.png">
