### ISSUE TITLE
[BADGE] Guild Leader

### ISSUE THREAD

**Issue by P3ter-NEARWEEK** [NEAR-Edu/stats.gallery#60]
**What is the name of the badge?**
Guild Leader

**When will the badge be awarded?**
When you found or run a guild

**Is this a series of badges (i.e. different badges awarded for different degrees of completion)?**
This is a one-off badge showing your connection and OG in the ecosystem

**Provide a simple SVG icon for the badge**

**What color(s) would you prefer the badge to be?**
No preferences

**Is this badge associated with a particular organization, product, or service?**
Yes: The specific guild you lead

**Does this badge link somewhere?**

No

**Comment by starpause** [comment]
This achievement is the SUPER RARE / EPIC levels of the [DAO-ist badge](https://github.com/NEAR-Edu/stats.gallery/issues/58).

**Comment by P3ter-NEARWEEK** [comment]
Cool!
