### ISSUE TITLE
Twitter button shares wrong page link

### ISSUE THREAD

**Issue by encody** [NEAR-Edu/stats.gallery#68]
**Describe the bug**
Clicking on the "Tweet" button when on the leaderboards page opens a prefilled tweet that says "Check out my NEAR stats" but with a link to the leaderboards page.

**To Reproduce**
1. Navigate to a NEAR account's overview page
2. Click on the "Leaderboards" navigation link
3. Reload the page
4. Click on the "Tweet" button in the header

**Expected behavior**
Either the text of the tweet is something like "Check out the leaderboards on NEAR" with the link to leaderboards, or it shares the link to the user's overview page with the original tweet text.

**Screenshots**

<img width="461" alt="brave_2021-10-14-14-10-42" src="https://user-images.githubusercontent.com/7459638/137380750-87e9c2f4-0f47-428f-803b-7cbc87d1ce6b.png">

**Additional context**
I have seen real tweets with this bug.

**Comment by akshajb** [comment]
Hey @encody I would like to take this issue up.

**Comment by encody** [comment]
@akshajb we'd love the help! Submit a PR with your fix and I'd be happy to review it

**Comment by akshajb** [comment]
@encody  I had a small query. Any particular reason the leaderboard route is routed via path and not via name like the others ?
![image](https://user-images.githubusercontent.com/19529446/137576922-1003686c-76c1-4c58-8324-4d91471fe581.png)

**Comment by encody** [comment]
Discussion on https://github.com/NEAR-Edu/stats.gallery/pull/70 elaborates on more facets of the issue.

**Comment by encody** [comment]
Fixed by https://github.com/NEAR-Edu/stats.gallery/pull/72
