### ISSUE TITLE
mainnet SITE DOWN !

### ISSUE THREAD

**Issue by danielwpz** [NEAR-Edu/stats.gallery#74]
most of the apis of mainnet is down.

e.g. `https://api.stats.gallery/mainnet/sent-transaction-count?account_id=danielwpz.near&after_block_timestamp=1638101546551000000&before_block_timestamp=1638706346551000000`

returns 404

**Comment by encody** [comment]
Yeah, the public indexer is rejecting SQL connections. We're working on
setting up our own indexer in the meantime. Sorry about that!

**Comment by danielwpz** [comment]
@encody hi, any luck on the indexer?

**Comment by encody** [comment]
@danielwpz Thanks for checking, it's about 1/4 of the way done syncing, last I checked. @Bexanderthebex is working on that project. Sorry it's been down for so long :( On the plus side, we're working on some really cool new features, so stats.gallery will be even more fun to use once the indexer is back online!

**Comment by encody** [comment]
Also, it's been taking about 1 hour per 1%, so... yeah, it's slow.

**Comment by Bexanderthebex** [comment]
Hey @danielwpz! sorry about this. We are working on restoring this service but would require some infrastructure upgrades first before we can restore it back. Basically, the public indexer that we are previously using is now being used by a lot of people and that is preventing our application from getting consistent connections. We are constantly working on this and we appreciate your patience on this matter.

**Comment by encody** [comment]
@danielwpz stats.gallery is back up using the new public indexer connections. Tentatively hoping this is solved.

**Comment by danielwpz** [comment]
yeah I saw it's back again lol! thanks.

btw this site is really useful, hope it could be more stable in the future :D

**Comment by encody** [comment]
@danielwpz I hope so too! Also check out the new feature that just got released: https://gov.near.org/t/smart-contract-explorer-on-stats-gallery/11232
